### ISSUE TITLE
EntryLine border does not take the full width on iPhone 6s

### ISSUE THREAD

**Issue by pkirillov** [jamesmontemagno/xamarin.forms-toolkit#3]
EntryLine border is rendered OK on iPhone 5s, but it does not take the full width on iPhone 6s. Refer to the screenshot and notice the darker background. So entry element is wider than border:

![screen shot 2016-04-29 at 1 14 58 pm](https://cloud.githubusercontent.com/assets/1530570/14914647/6c84812c-0e0c-11e6-8c8d-138516010735.png)

**Comment by jamesmontemagno** [comment]
Fixed with #5
