### ISSUE TITLE
More controls please

### ISSUE THREAD

**Issue by weitzhandler** [jamesmontemagno/xamarin.forms-toolkit#7]
Hi,

This suggestion applies to XF in general, but I thought it might belong here.

Currently, XF lacks some elementary controls, such as `CheckBox`, `RadioButton`, `RadioButtonGroup`, `DateTimePicker`, `MultiPicker`, `AutoCompleteView`, `ItemsView` (`ItemsControl`), [improvements to `ListView`](https://forums.xamarin.com/discussion/98053/please-improve-listview) (`Horizontal` orientation and more), `ImageButton`.

I know some of the controls exist in XLabs etc., but those are outdated, doesn't support all platforms, and are really buggy. Xamarin should really take sponsorship of a community toolkit and design clear guidelines  of developing these controls.  
Any developer who wants to create an extensive forms-driven app and will have to use any of the above controls will have to spend a great deal of time developing and testing these controls, times target platforms!

I wish Xamarin introduces a new namespace such as `Xamarin.Forms.Controls` or `Xamarin.Forms.NonNative` that includes all these controls that have a platform that doesn't provide its native functionality. These controls are mandatory, and its lack really makes no sense.
XF should aim to cover the UI functionality Ionic provides, be it native or not. Because development time counts not less than performance time!

Cross posted [here](https://xamarin.uservoice.com/forums/258559-xamarin-forms-suggestions/suggestions/19095433-more-controls).

**Comment by jamesmontemagno** [comment]
These efforts have moved to: https://github.com/formscommunitytoolkit

**Comment by weitzhandler** [comment]
WOW amazing!
Thanks for your quick response!

**Comment by weitzhandler** [comment]
The Xamarin toolkit would be very promising, but in fact it doesn't look like there is much traffic there (talking about the controls).
I'd love to contribute to tasks I'm given.
